[env:lilygo_t_display]
platform = espressif32
board = esp32dev
framework = arduino

monitor_speed = 9600
upload_speed = 921600

lib_deps =
    bodmer/TFT_eSPI

build_flags =
    -D USER_SETUP_LOADED
    -include lib/TFT_eSPI_Setup/User_Setup.h
